/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'on-secondary-fixed-variant': '#005049',
        'inverse-surface': '#213145',
        'on-primary-fixed-variant': '#3f465c',
        'on-surface': '#0b1c30',
        'primary-container': '#131b2e',
        surface: '#f8f9ff',
        'tertiary-container': '#001a42',
        'secondary-fixed-dim': '#6bd8cb',
        'inverse-primary': '#bec6e0',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'on-primary-fixed': '#131b2e',
        'secondary-container': '#86f2e4',
        'secondary-fixed': '#89f5e7',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'on-tertiary-container': '#3980f4',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#004395',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#00201d',
        'tertiary-fixed-dim': '#adc6ff',
        'tertiary-fixed': '#d8e2ff',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary-fixed': '#001a42',
        secondary: '#006a61',
        'surface-container-highest': '#d3e4fe',
        'primary-fixed-dim': '#bec6e0',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#7c839b',
        background: '#f8f9ff',
        'on-secondary-container': '#006f66',
        tertiary: '#000000',
        'outline-variant': '#c6c6cd',
        outline: '#76777d',
        'primary-fixed': '#dae2fd',
        primary: '#000000',
        'on-background': '#0b1c30',
        'on-surface-variant': '#45464d',
        'surface-tint': '#565e74',
        'surface-variant': '#d3e4fe',
        'surface-container-high': '#dce9ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '8px',
        sm: '16px',
        gutter: '24px',
        base: '4px',
        md: '24px',
        'container-max': '1440px',
        lg: '32px',
        xl: '48px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-sm': ['Inter'],
        'body-lg': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
